=== AlphaOrange/binder/resources/schemas/schema_character.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "character",
  "description": "A character description file for binder",
  "type": "object",
  "additionalProperties": false,
  "required": ["Typ","ID", "Name", "Geburtsjahr"],
  "properties": {
    "Typ": {
      "type": "string"
    },
    "ID": {
      "type": "string",
      "pattern": "^[a-z][a-z0-9]*$"
    },
    "Name": {
      "type": "string"
    },
    "Tags": {
      "type": "object",
      "patternProperties": {
        "^[A-ZÄÖÜ][A-ZÄÖÜa-zäöüß]*$": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      }
    },
    "Rolle": {
      "type": "string",
      "enum": ["primary", "recurring", "once", "mention"]
    },
    "Titel": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "Profession": {
      "type": "string"
    },
    "Geschlecht": {
      "type": "string",
      "enum": ["m", "w", "d"]
    },
    "Geburtsjahr": {
      "type": "integer"
    },
    "Todesjahr": {
      "type": "integer"
    },
    "Bilder": {
      "type": "array",
      "items": {
        "type": "string",
        "pattern": "^[^\\\\\\/\\.]+\\.(jpg|png)$"
      }
    },
    "Erscheinung": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "Aussehen": {
          "type": "string"
        },
        "Kleidung": {
          "type": "string"
        },
        "Gestik": {
          "type": "string"
        },
        "Mimik": {
          "type": "string"
        },
        "Stimme": {
          "type": "string"
        },
        "Besonderheiten": {
          "type": "string"
        }
      }
    },
    "Kampagnen": {
      "type": "array",
      "items": {
        "type": "string",
        "pattern": "^[a-zäöüß]+$"
      }
    },
    "Text": {
      "type": "string"
    },
    "Inventar": {
      "type": "object",
      "patternProperties": {
        "^.*$": {
          "type": "integer"
        }
      }
    },
    "Spezies": {
      "type": "string",
      "enum": ["Mensch", "Elf", "Halbelf", "Zwerg"]
    },
    "Sprachen": {
      "type": "object",
      "patternProperties": {
        "^[a-zA-Z\\- ]+$": {
          "type": "integer"
        }
      },
      "additionalProperties": false
    },
    "Schriften": {
      "type": "array",
      "items": {
        "pattern": "^[a-zA-Z\\- ]+$"
      }
    },
    "Stats": {
      "type": "object",
      "properties": {
        "Grundwerte": {
          "type": "object",
          "patternProperties": {
            "^LeP|AsP|KaP|SK|ZK|AW|INI|GS$": {
              "type": "integer"
            }
          },
          "additionalProperties": false,
          "minProperties": 8
        },
        "Eigenschaften": {
          "type": "object",
          "patternProperties": {
            "^MU|KL|IN|CH|FF|GE|KO|KK$": {
              "type": "integer"
            }
          },
          "additionalProperties": false,
          "minProperties": 8
        },
        "Fertigkeiten": {
          "type": "object",
          "patternProperties": {
            "^[A-ZÄÖÜ][A-ZÄÖÜa-zäöüß& ]*$": {
              "type": "integer"
            }
          },
          "additionalProperties": false
        },
        "Kampftechniken": {
          "type": "object",
          "patternProperties": {
            "^[A-ZÄÖÜ][A-ZÄÖÜa-zäöüß& ]*$": {
              "type": "integer"
            }
          },
          "additionalProperties": false
        },
        "Rüstungsschutz": {
          "type": "integer"
        },
        "Waffen": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "Nahkampf": {
              "type": "object",
              "properties": {
                "^[A-ZÄÖÜ][A-ZÄÖÜa-zäöüß& ]*$": {
                  "type": "object",
                  "additionalProperties": false,
                  "minProperties": 6,
                  "properties": {
                    "AT": {
                      "type": "integer"
                    },
                    "PA": {
                      "type": "integer"
                    },
                    "TP": {
                      "type": "array",
                      "items": {
                        "type": "integer"
                      },
                      "minItems": 2,
                      "maxItems": 2
                    },
                    "RW": {
                      "type": "string",
                      "enum": ["kurz", "mittel", "lang"]
                    },
                    "Vorteil": {
                      "type": ["string", "null"]
                    },
                    "Nachteil": {
                      "type": ["string", "null"]
                    }
                  }
                }
              }
            },
            "Fernkampf": {
              "type": "object",
              "properties": {
                "^[A-ZÄÖÜ][A-ZÄÖÜa-zäöüß& ]*$": {
                  "type": "object",
                  "additionalProperties": false,
                  "minProperties": 6,
                  "properties": {
                    "FK": {
                      "type": "integer"
                    },
                    "TP": {
                      "type": "array",
                      "items": {
                        "type": "integer"
                      },
                      "minItems": 2,
                      "maxItems": 2
                    },
                    "LZ": {
                      "type": "integer"
                    },
                    "RW": {
                      "type": "array",
                      "items": {
                        "type": "integer"
                      },
                      "minItems": 3,
                      "maxItems": 3
                    },
                    "Munition": {
                      "type": "integer"
                    },
                    "Vorteil": {
                      "type": ["string", "null"]
                    },
                    "Nachteil": {
                      "type": ["string", "null"]
                    }
                  }
                }
              }
            }
          }
        },
        "Magie": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "Zaubersprüche": {
              "type": "object",
              "patternProperties": {
                "^[A-ZÄÖÜ][A-ZÄÖÜa-zäöüß& ]*$": {
                  "type": "array",
                  "items": [
                    {
                      "type": "integer"
                    }
                  ],
                  "additionalItems": {
                    "type": "string"
                  }
                }
              },
              "additionalProperties": false
            },
            "Rituale": {
              "type": "object",
              "patternProperties": {
                "^[A-ZÄÖÜ][A-ZÄÖÜa-zäöüß& ]*$": {
                  "type": "array",
                  "items": [
                    {
                      "type": "integer"
                    }
                  ],
                  "additionalItems": {
                    "type": "string"
                  }
                }
              },
              "additionalProperties": false
            },
            "Zaubertricks": {
              "type": "array",
              "items": {
                "type": "string"
              }
            }
          }
        },
        "Götterwirken": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "Liturgien": {
              "type": "object",
              "patternProperties": {
                "^[A-ZÄÖÜ][A-ZÄÖÜa-zäöüß& ]*$": {
                  "type": "array",
                  "items": [
                    {
                      "type": "integer"
                    }
                  ],
                  "additionalItems": {
                    "type": "string"
                  }
                }
              },
              "additionalProperties": false
            },
            "Zeremonien": {
              "type": "object",
              "patternProperties": {
                "^[A-ZÄÖÜ][A-ZÄÖÜa-zäöüß& ]*$": {
                  "type": "array",
                  "items": [
                    {
                      "type": "integer"
                    }
                  ],
                  "additionalItems": {
                    "type": "string"
                  }
                }
              },
              "additionalProperties": false
            },
            "Segnungen": {
              "type": "array",
              "items": {
                "type": "string"
              }
            }
          }
        }
      },
      "additionalProperties": false,
      "minProperties": 7
    },
    "Vorteile": {
      "type": "object",
      "patternProperties": {
        "^[A-ZÄÖÜ][A-ZÄÖÜa-zäöüß& ]*$": {
          "type": "array",
          "items": {
            "type": ["string", "integer"]
          }
        }
      }
    },
    "Nachteile": {
      "type": "object",
      "patternProperties": {
        "^[A-ZÄÖÜ][A-ZÄÖÜa-zäöüß& ]*$": {
          "type": "array",
          "items": {
            "type": ["string", "integer"]
          }
        }
      }
    },
    "Sonderfertigkeiten": {
      "type": "object",
      "patternProperties": {
        "^[A-ZÄÖÜ][A-ZÄÖÜa-zäöüß& ]*$": {
          "type": "array",
          "items": {
            "type": ["string", "integer"]
          }
        }
      }
    },
    "Sonderregeln": {
      "type": "object",
      "patternProperties": {
        "^[A-ZÄÖÜ][A-ZÄÖÜa-zäöüß& ]*$": {
          "type": "string"
        }
      }
    }
  }
}

=== AlphaOrange/binder/data/characters/biko.json
{
  "Typ": "character",
  "ID": "biko",
  "Name": "Biko",
  "Tags": {
    "Arcs": [],
    "Orte": ["Honingen", "Galebfurt"],
    "Weitere": []
  },
  "Rolle": "recurring",
  "Titel": [],
  "Profession": "Bettler",
  "Geschlecht": "m",
  "Geburtsjahr": 1004,
  "Bilder": [
    "char_biko.png"
  ],
  "Kampagnen": ["abilacht", "zkin"],
  "Text": "Biko, der Bettler, lebt in Honingen auf der Straße. Er verfügt ohne es selbst zu wissen über die Gabe der intuitiven Magie und liest manchmal die Gedanken von Passanten, wodurch er wertvolle Informationen aufschnappen kann, aber auch unnheimlich wirkt, wenn er Menschen auf Dinge anspricht, von denen er eigentlich nichts wissen dürfte.\nEr kennt das Loch von Galebfurt, wo er seiner Hinrichtung nur knapp entrinnen konnte.",
  "Inventar": {
  },
  "Spezies": "Mensch",
  "Sprachen": {
  },
  "Schriften": [],
  "Stats": {
    "Grundwerte": {
      "LeP": 0,
      "AsP": 0,
      "KaP": 0,
      "SK": 0,
      "ZK": 0,
      "AW": 0,
      "INI": 0,
      "GS": 0
    },
    "Eigenschaften": {
      "MU": 13,
      "KL": 10,
      "IN": 16,
      "CH": 9,
      "FF": 11,
      "GE": 9,
      "KO": 8,
      "KK": 10
    },
    "Fertigkeiten": {},
    "Kampftechniken": {
      "Armbrüste": 6,
      "Bögen": 6,
      "Wurfwaffen": 6,
      "Dolche": 6,
      "Fechtwaffen": 6,
      "Hiebwaffen": 6,
      "Kettenwaffen": 6,
      "Lanzen": 6,
      "Raufen": 6,
      "Schilde": 6,
      "Schwerter": 6,
      "Stangenwaffen": 6,
      "Zweihandhiebwaffen": 6,
      "Zweihandschwerter": 6
    },
    "Rüstungsschutz": 0,
    "Waffen": {},
    "Magie": {
      "Zaubersprüche": {
      },
      "Rituale": {
      },
      "Zaubertricks": []
    },
    "Götterwirken": {
      "Liturgien": {
      },
      "Zeremonien": {
      },
      "Segnungen": []
    }
  },
  "Vorteile": {
  },
  "Nachteile": {
  },
  "Sonderfertigkeiten": {
  },
  "Sonderregeln": {
  }
}

=== AlphaOrange/binder/data/characters/m_galebfurt.json
[
  {
    "Typ": "character",
    "ID": "alphak",
    "Name": "Alphak",
    "Tags": { "Orte": ["Galebfurt", "Trappenfurt"] },
    "Rolle": "once",
    "Geschlecht": "m",
    "Geburtsjahr": 1023
  },
  {
    "Typ": "character",
    "ID": "growin",
    "Name": "Growin",
    "Tags": { "Orte": ["Galebfurt", "Trappenfurt"] },
    "Rolle": "once",
    "Geschlecht": "m",
    "Geburtsjahr": 1029
  }
]

=== AlphaOrange/binder/data/characters/wolfram.json
{
  "Typ": "character",
  "ID": "wolfram",
  "Name": "Wolfram Silberschmitt",
  "Tags": {
    "Arcs": [],
    "Orte": ["Honingen"],
    "Weitere": []
  },
  "Rolle": "recurring",
  "Titel": [],
  "Profession": "Alchemist",
  "Geschlecht": "m",
  "Geburtsjahr": 1004,
  "Bilder": [
    "char_Wolfram.png"
  ],
  "Kampagnen": ["zkin", "dasloch"],
  "Text": "Ein Alchemist mit unzähligen Verbindungen in Alchemistenkreise. Seine Neugier hat gesiegt, als er sich von Minverva bei der Abenteuerergilde anheuern ließ, jedoch merkte er schnell, dass er seine Zeit viel lieber im Labor oder auf Kongressen verbringt als sein Leben in irgendwelchen verfallenen Tempeln zu verbringen. Wenn er nicht gerade unterwegs ist, im sich mit Collegae auszutauschen ist er also in seinem Labor zu finden.",
  "Inventar": {
  },
  "Spezies": "Mensch",
  "Sprachen": {
  },
  "Schriften": [],
  "Stats": {
    "Grundwerte": {
      "LeP": 0,
      "AsP": 0,
      "KaP": 0,
      "SK": 0,
      "ZK": 0,
      "AW": 0,
      "INI": 0,
      "GS": 0
    },
    "Eigenschaften": {
      "MU": 10,
      "KL": 16,
      "IN": 14,
      "CH": 14,
      "FF": 14,
      "GE": 10,
      "KO": 12,
      "KK": 10
    },
    "Fertigkeiten": {},
    "Kampftechniken": {
      "Armbrüste": 6,
      "Bögen": 6,
      "Wurfwaffen": 6,
      "Dolche": 6,
      "Fechtwaffen": 6,
      "Hiebwaffen": 6,
      "Kettenwaffen": 6,
      "Lanzen": 6,
      "Raufen": 6,
      "Schilde": 6,
      "Schwerter": 6,
      "Stangenwaffen": 6,
      "Zweihandhiebwaffen": 6,
      "Zweihandschwerter": 6
    },
    "Rüstungsschutz": 0,
    "Waffen": {
      "Nahkampf": {
      },
      "Fernkampf": {
      }
    },
    "Magie": {
      "Zaubersprüche": {
      },
      "Rituale": {
      },
      "Zaubertricks": []
    },
    "Götterwirken": {
      "Liturgien": {
      },
      "Zeremonien": {
      },
      "Segnungen": []
    }
  },
  "Vorteile": {
  },
  "Nachteile": {
  },
  "Sonderfertigkeiten": {
  },
  "Sonderregeln": {
  }
}

=== AlphaOrange/binder/data/characters/jalosch.json
{
  "Typ": "character",
  "ID": "baronjalosch",
  "Name": "Jalosch von Gernebruch",
  "Tags": {
    "Arcs": [],
    "Orte": ["Gernebruch", "Galebfurt", "Trappenfurt"],
    "Weitere": []
  },
  "Rolle": "recurring",
  "Titel": [
    "Baron"
  ],
  "Profession": "Adliger",
  "Geschlecht": "m",
  "Geburtsjahr": 993,
  "Bilder": [
    "char_Baron.png"
  ],
  "Kampagnen": ["dasloch"],
  "Text": "Der Baron verfügt über das Dorf Gernebruch, das von seinem Vater Jarolan von Gernebruch gewaltsam aus der Baronie Trappenfurten erobert wurde. Er weiß vom Loch der Verdammten und hat 1020 dessen Wiederöffnung selbst angeordnet, als er einen politischen Widersacher hinrichten ließ.",
  "Inventar": {
  },
  "Spezies": "Mensch",
  "Sprachen": {
  },
  "Schriften": [],
  "Stats": {
    "Grundwerte": {
      "LeP": 0,
      "AsP": 0,
      "KaP": 0,
      "SK": 0,
      "ZK": 0,
      "AW": 0,
      "INI": 0,
      "GS": 0
    },
    "Eigenschaften": {
      "MU": 11,
      "KL": 15,
      "IN": 13,
      "CH": 15,
      "FF": 14,
      "GE": 10,
      "KO": 11,
      "KK": 14
    },
    "Fertigkeiten": {},
    "Kampftechniken": {
      "Armbrüste": 6,
      "Bögen": 6,
      "Wurfwaffen": 6,
      "Dolche": 6,
      "Fechtwaffen": 6,
      "Hiebwaffen": 6,
      "Kettenwaffen": 6,
      "Lanzen": 6,
      "Raufen": 6,
      "Schilde": 6,
      "Schwerter": 6,
      "Stangenwaffen": 6,
      "Zweihandhiebwaffen": 6,
      "Zweihandschwerter": 6
    },
    "Rüstungsschutz": 0,
    "Waffen": {
    },
    "Magie": {},
    "Götterwirken": {
    }
  },
  "Vorteile": {
  },
  "Nachteile": {
  },
  "Sonderfertigkeiten": {
  },
  "Sonderregeln": {
  }
}

=== AlphaOrange/binder/data/characters/zasar.json
{
  "Typ": "character",
  "ID": "zasar",
  "Name": "Zasar Caradir",
  "Tags": {
    "Arcs": ["Zasar"],
    "Orte": ["Gareth", "Maraskan", "Selem", "Vinsalt"],
    "Weitere": ["Wissen"]
  },
  "Rolle": "recurring",
  "Titel": [],
  "Profession": "Archäologe",
  "Geschlecht": "m",
  "Geburtsjahr": 993,
  "Bilder": [
    "char_Zasar.png"
  ],
  "Kampagnen": ["dschungelpfade", "zkin"],
  "Text": "Entdecker aus Gareth, der unlängst durch einen Gestaltwandler ersetzt wurde, den er versehentlich aus Alt-Belhanka befreite. Dieser ist seither auf der Jagd nach den vier Iribaarsspiegeln.",
  "Inventar": {
  },
  "Spezies": "Mensch",
  "Sprachen": {
  },
  "Schriften": [],
  "Stats": {
    "Grundwerte": {
      "LeP": 0,
      "AsP": 0,
      "KaP": 0,
      "SK": 0,
      "ZK": 0,
      "AW": 0,
      "INI": 0,
      "GS": 0
    },
    "Eigenschaften": {
      "MU": 15,
      "KL": 15,
      "IN": 13,
      "CH": 15,
      "FF": 11,
      "GE": 14,
      "KO": 14,
      "KK": 12
    },
    "Fertigkeiten": {},
    "Kampftechniken": {
      "Armbrüste": 6,
      "Bögen": 6,
      "Wurfwaffen": 6,
      "Dolche": 6,
      "Fechtwaffen": 6,
      "Hiebwaffen": 6,
      "Kettenwaffen": 6,
      "Lanzen": 6,
      "Raufen": 6,
      "Schilde": 6,
      "Schwerter": 6,
      "Stangenwaffen": 6,
      "Zweihandhiebwaffen": 6,
      "Zweihandschwerter": 6
    },
    "Rüstungsschutz": 0,
    "Waffen": {
    },
    "Magie": {},
    "Götterwirken": {
    }
  },
  "Vorteile": {
  },
  "Nachteile": {
  },
  "Sonderfertigkeiten": {
  },
  "Sonderregeln": {
  }
}

=== AlphaOrange/binder/data/characters/nelda.json
{
  "Typ": "character",
  "ID": "nelda",
  "Name": "Nelda Rappenstein",
  "Tags": {
    "Arcs": [],
    "Orte": ["Galebfurt"],
    "Weitere": []
  },
  "Rolle": "once",
  "Titel": [],
  "Profession": "Söldnerin",
  "Geschlecht": "w",
  "Geburtsjahr": 1009,
  "Bilder": [
    "char_Nelda.png"
  ],
  "Kampagnen": ["dasloch"],
  "Text": "Fing als Rattenfängerin für die verschiedenen Siedlungen des Barons an, wurde dann aber in Galebfurt sesshaft, weil sie sich trickreich im Kampf gegen die Ghule erwies. Heute steht sie der Gernebrucher Ghulgarde vor, die aus ihr und zwei Mitstreitern besteht.",
  "Inventar": {
  },
  "Spezies": "Mensch",
  "Sprachen": {
  },
  "Schriften": [],
  "Stats": {
    "Grundwerte": {
      "LeP": 0,
      "AsP": 0,
      "KaP": 0,
      "SK": 0,
      "ZK": 0,
      "AW": 0,
      "INI": 0,
      "GS": 0
    },
    "Eigenschaften": {
      "MU": 16,
      "KL": 11,
      "IN": 15,
      "CH": 10,
      "FF": 14,
      "GE": 14,
      "KO": 13,
      "KK": 12
    },
    "Fertigkeiten": {},
    "Kampftechniken": {
      "Armbrüste": 6,
      "Bögen": 6,
      "Wurfwaffen": 6,
      "Dolche": 6,
      "Fechtwaffen": 6,
      "Hiebwaffen": 6,
      "Kettenwaffen": 6,
      "Lanzen": 6,
      "Raufen": 6,
      "Schilde": 6,
      "Schwerter": 6,
      "Stangenwaffen": 6,
      "Zweihandhiebwaffen": 6,
      "Zweihandschwerter": 6
    },
    "Rüstungsschutz": 0,
    "Waffen": {
      "Nahkampf": {
      },
      "Fernkampf": {
      }
    },
    "Magie": {
      "Zaubersprüche": {
      },
      "Rituale": {
      },
      "Zaubertricks": []
    },
    "Götterwirken": {
      "Liturgien": {
      },
      "Zeremonien": {
      },
      "Segnungen": []
    }
  },
  "Vorteile": {
  },
  "Nachteile": {
  },
  "Sonderfertigkeiten": {
  },
  "Sonderregeln": {
  }
}

=== AlphaOrange/binder/data/characters/gustavus.json
{
  "Typ": "character",
  "ID": "gustavus",
  "Name": "Gustavus Eibenfeld",
  "Tags": {
    "Arcs": ["Zasar"],
    "Orte": ["Gareth", "Honingen"],
    "Weitere": []
  },
  "Rolle": "recurring",
  "Titel": [],
  "Profession": "Archivar",
  "Geschlecht": "m",
  "Geburtsjahr": 1012,
  "Bilder": [
    "char_Gustavus.png"
  ],
  "Kampagnen": ["dschungelpfade", "zkin", "dasloch"],
  "Text": "Archivar der Akademie Stab und Schwert zu Gareth. Er hat eine Passion für Magiegeschichte und mächtige Artefakte, aber die meisten Akademiemagier interessieren sich nicht dafür, weshalb er oft mit Helden von außerhalb arbeitet.",
  "Inventar": {
  },
  "Spezies": "Mensch",
  "Sprachen": {
  },
  "Schriften": [],
  "Stats": {
    "Grundwerte": {
      "LeP": 0,
      "AsP": 0,
      "KaP": 0,
      "SK": 0,
      "ZK": 0,
      "AW": 0,
      "INI": 0,
      "GS": 0
    },
    "Eigenschaften": {
      "MU": 10,
      "KL": 15,
      "IN": 14,
      "CH": 10,
      "FF": 13,
      "GE": 11,
      "KO": 14,
      "KK": 12
    },
    "Fertigkeiten": {},
    "Kampftechniken": {
      "Armbrüste": 6,
      "Bögen": 6,
      "Wurfwaffen": 6,
      "Dolche": 6,
      "Fechtwaffen": 6,
      "Hiebwaffen": 6,
      "Kettenwaffen": 6,
      "Lanzen": 6,
      "Raufen": 6,
      "Schilde": 6,
      "Schwerter": 6,
      "Stangenwaffen": 6,
      "Zweihandhiebwaffen": 6,
      "Zweihandschwerter": 6
    },
    "Rüstungsschutz": 0,
    "Waffen": {
    },
    "Magie": {
      "Zaubersprüche": {
      },
      "Rituale": {
      },
      "Zaubertricks": []
    },
    "Götterwirken": {
      "Liturgien": {
      },
      "Zeremonien": {
      },
      "Segnungen": []
    }
  },
  "Vorteile": {
  },
  "Nachteile": {
  },
  "Sonderfertigkeiten": {
  },
  "Sonderregeln": {
  }
}

=== AlphaOrange/binder/data/characters/morena.json
{
  "Typ": "character",
  "ID": "morena",
  "Name": "Morena Mangold",
  "Tags": {
    "Arcs": [],
    "Orte": ["Galebfurt"],
    "Weitere": []
  },
  "Rolle": "once",
  "Titel": [],
  "Profession": "Söldnerin",
  "Geschlecht": "w",
  "Geburtsjahr": 1001,
  "Todesjahr": 1038,
  "Bilder": [
    "char_Morena.png",
    "char_Morena_Zombie.png",
    "char_Morena2.png"
  ],
  "Kampagnen": ["dasloch"],
  "Text": "Eine Söldnerin aus der freien Stadt Lowangen, die sich in zahlreichen Kämpfen gegen die Orks bewährte. Dabei fiel allerdings ihr Blutrausch immer wieder zum Problem, in dem sie außerdem die Leichen ihrer Feinde schändet und deren Heimat plündert. Nachdem ihr eine schwere Niederlage gegen die Ork angehängt wurde, zog sie nach Süden und diente als Söldnerin, wobei sie ihre Auftraggeber selten genau prüfte. So nahm sie ohne dies genau zu wissen, an einem Raub an einer kaiserlichen Warenkolonne zur Akademie teil, wo sie Schmuck und ein mächtiges Artefakt entwendete und floh anschließend verletzt nach Galebfurt. Dort starb sie an ihren Wunden und wurde ins Loch der Verdammten geworfen. Der Nekromant Tann holte sie als Zombie zurück.",
  "Inventar": {
  },
  "Spezies": "Mensch",
  "Sprachen": {
  },
  "Schriften": [],
  "Stats": {
    "Grundwerte": {
      "LeP": 0,
      "AsP": 0,
      "KaP": 0,
      "SK": 0,
      "ZK": 0,
      "AW": 0,
      "INI": 0,
      "GS": 0
    },
    "Eigenschaften": {
      "MU": 22,
      "KL": 6,
      "IN": 10,
      "CH": 6,
      "FF": 8,
      "GE": 10,
      "KO": 13,
      "KK": 15
    },
    "Fertigkeiten": {},
    "Kampftechniken": {
      "Armbrüste": 6,
      "Bögen": 6,
      "Wurfwaffen": 6,
      "Dolche": 6,
      "Fechtwaffen": 6,
      "Hiebwaffen": 6,
      "Kettenwaffen": 6,
      "Lanzen": 6,
      "Raufen": 6,
      "Schilde": 6,
      "Schwerter": 6,
      "Stangenwaffen": 6,
      "Zweihandhiebwaffen": 6,
      "Zweihandschwerter": 6
    },
    "Rüstungsschutz": 0,
    "Waffen": {
    },
    "Magie": {
      "Zaubersprüche": {
      },
      "Rituale": {
      },
      "Zaubertricks": []
    },
    "Götterwirken": {
      "Liturgien": {
      },
      "Zeremonien": {
      },
      "Segnungen": []
    }
  },
  "Vorteile": {
  },
  "Nachteile": {
  },
  "Sonderfertigkeiten": {
  },
  "Sonderregeln": {
  }
}
