=== AlphaOrange/binder/resources/schemas/schema_campaign.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "campaign",
  "description": "A campaign description file for binder",
  "type": "object",
  "additionalProperties": false,
  "required": ["Typ","ID", "Name"],
  "properties": {
    "Typ": {
      "type": "string"
    },
    "ID": {
      "type": "string",
      "pattern": "^[a-z][a-z0-9]*$"
    },
    "Name": {
      "type": "string"
    },
    "Tags": {
      "type": "object",
      "patternProperties": {
        "^[A-ZÄÖÜ][A-ZÄÖÜa-zäöüß]*$": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      }
    },
    "Nummer": {
      "type": ["integer", "null"]
    },
    "Titelbilder": {
      "type": "array",
      "items": {
        "type": "string",
        "pattern": "^[^\\\\\\/\\.]+\\.(jpg|png)$"
      }
    },
    "Text": {
      "type": "string"
    }
  }
}

=== AlphaOrange/binder/data/campaigns/13-flaschengeist.json
{
  "Typ": "campaign",
  "ID": "flaschengeist",
  "Name": "Der Geist in der Flasche",
  "Tags": {
    "Arcs": []
  },
  "Titelbilder": [],
  "Text": "Shanhazadrakhadifa, der Flaschengeist der Gruppe, wünscht sich, dass die Gruppe in ihrer Flasche ihre verschwundene Schwester wiederfindet. Dort tauchen die Helden in die finstere Vergangenheit ihrer Begleiterin ein und finden heraus, worum es sich beim Geist und ihrer Flasche tatsächlich handelt."
}

=== AlphaOrange/binder/data/campaigns/3-sicmundus.json
{
  "Typ": "campaign",
  "ID": "sicmundus",
  "Name": "Sic Mundus",
  "Tags": {
    "Arcs": []
  },
  "Nummer": 3,
  "Titelbilder": [],
  "Text": "Auf einer Seereise gerät die Mannschaft der Brünstigen Maria in einen Sturm, der das Schiff in eine rückwärts durch die Zeit wandernde Globule befördert. Diese wurde in der Zukunft von Magiern als Utopia für freie Forschung geschaffen, geriet aber außer Kontrolle und wurde stattdessen als Gefängnis für Schwerverbrecher verwendet."
}

=== AlphaOrange/binder/data/campaigns/5-abilacht.json
{
  "Typ": "campaign",
  "ID": "abilacht",
  "Name": "Geister in Abilacht",
  "Tags": {
    "Arcs": []
  },
  "Nummer": 5,
  "Titelbilder": [],
  "Text": "In Abilacht wurde nächtliches Geistertreiben beobachtet. Tatsächlich handelt es sich um Mumien, die mit einem Grolm in Zusammenhang stehen, den die Bewohner in den Untergrund vertrieben haben."
}

=== AlphaOrange/binder/data/campaigns/6-dschungelpfade.json
{
  "Typ": "campaign",
  "ID": "dschungelpfade",
  "Name": "Dschungelpfade",
  "Tags": {
    "Arcs": ["Zasar", "Arena Arcana"],
    "Weitere": ["Hexploration"]
  },
  "Nummer": 6,
  "Titelbilder": [],
  "Text": "Nahe Gareth wird der nicht verwesende Körper des Expeditionsleisters Zasar Caradir gefunden. Die Gruppe reist im Auftrag von Zasars Kollegen Gustavus Eibenfeld nach Maraskan, um den Fall zu klären und herauszufinden, was mit den übrigen Mitgliedern der Expedition geschehen ist."
}

=== AlphaOrange/binder/data/campaigns/11-dasloch.json
{
  "Typ": "campaign",
  "ID": "dasloch",
  "Name": "Das Loch der Verdammten",
  "Tags": {
    "Arcs": []
  },
  "Nummer": 11,
  "Titelbilder": [],
  "Text": "Auf der Suche nach der Plünderin Morena Mangold gerät die Gruppe in ein Dorf, das seine Toten in einem tiefen Loch entsorgt und seit Kurzem von diesen wieder heimgesucht wird."
}

=== AlphaOrange/binder/data/campaigns/10-kessel.json
{
  "Typ": "campaign",
  "ID": "kessel",
  "Name": "Der Kessel",
  "Tags": {
    "Arcs": ["Insektenkrieg"]
  },
  "Nummer": 10,
  "Titelbilder": [],
  "Text": "Allerhand Schatzsucher und Glücksritter fallen in das Dorf Fiolbar ein, unter dem sich nicht nur ein Höhlensystem und ein verlassener Tempel befindet, sondern auch Hinterlassenschaften der frühen Insektenvölker."
}
